### ISSUE TITLE
Issues: The Mummery

### ISSUE THREAD

**Issue by EmmaSweeney** [ConcaveTrillion/ambrose-bierce_poetry#5]
- [x] The dramatis personaes need to be in sentence case.

- [x] In verse drama, the reason why some lines begin somewhere in the middle or right-side of the page is because these are interjections. You don't need to indent these lines. As you probably discovered the indents are all over the place! The first interjection is "Case of infra dig."

- [x] Some of the stage directions need to be restructured. The stage directions that are right-aligned are in-line stage directions and should be at the end of the previous verse line. This is common in Shakespeare. The stage directions that are left-aligned and indented go in their own stage-direction rows.

- [x] The stage-direction rows don't need `<p>` elements. Look at the example in [SEMOS 7.6.6.4](https://standardebooks.org/manual/1.7.0/single-page#7.6.6.4).

- [x] When there is a stage direction following the persona and before the verse/song, the first paragraph is the stage direction then followed by the song/verse all inside the same `<td>` element. It looks like you need to combine the stage directions with their dialog. For example,
![image](https://user-images.githubusercontent.com/56360562/191614861-949846a1-f069-4b15-b823-f70974da34d6.png)
Dead Cat's singing should be structured like:
```
							<tr>
								<td epub:type="z3998:persona">Dead Cat</td>
								<td>
									<p>
										<i epub:type="z3998:stage-direction">Singing.</i>
									</p>
									<blockquote epub:type="z3998:song">
										<p>
											<span>Merrily, merrily, round I go⁠—</span>
											<br/>
											<span class="i1">Over and under and at.</span>
											<br/>
											<span>Swing wide and free, swing high and low</span>
											<br/>
											<span class="i1">The anti-monopoly cat!</span>
										</p>
										<p>
											<span>O, who wouldn’t be in the place of me,</span>
											<br/>
											<span class="i1">The anti-monopoly cat?</span>
											<br/>
											<span class="i2">Designed to admonish,</span>
											<br/>
											<span class="i2">Persuade and astonish</span>
											<br/>
											<span>The capitalist and⁠—</span>
										</p>
									</blockquote>
								</td>
							</tr>
```
This can be very confusing! If you still don't understand or you encounter any trouble feel free to ask for more help.

- [x] At the end of the plays, "Curtain." is a high-level stage direction and should be outside of the dialog table. Take a look at the example in [SEMOS 7.6.7.3](https://standardebooks.org/manual/1.7.0/single-page#7.6.7.3).

- [x] Remove `rowspan` attributes where there is no `together` class.

- [x] There are several characters that don't have dialog. They should not be tagged as personas ([SEMOS 7.6.3](https://standardebooks.org/manual/1.7.0/single-page#7.6.3)) (ex. Moon, Blue Lights, Red Fire, Red Fire, Gas, Villiam, etc).

- [x] In Slickens, the stage direction `<i epub:type="z3998:stage-direction"><b epub:type="z3998:persona">Feegobble</b>, <b epub:type="z3998:persona">Ringdivvy</b>, <b epub:type="z3998:persona">Nozzle</b>.</i>` should go at the beginning of the scene. This also looks like a high-level stage direction and should be outside of the dialog table.

- [x] St. John needs to be tagged as a persona in `<i epub:type="z3998:stage-direction">Pours the liquid down <abbr>St.</abbr> John’s back.</i>`.

- [x] Grimghast needs to be tagged as a persona in `<i epub:type="z3998:stage-direction">To Grimghast.</i>`.

- [x] Smyler needs to be tagged as a persona in `<i epub:type="z3998:stage-direction">Enter Smyler.</i>`.

- [x] Smyler needs to be tagged as a persona in `<i epub:type="z3998:stage-direction">Exit Smyler.</i>`.

- [x] Needleson needs to be tagged as a persona in `<i epub:type="z3998:stage-direction">Exit Needleson.</i>`.

- [x] Hoodos needs to be tagged as a persona in `<i epub:type="z3998:stage-direction">Exeunt Hoodos.</i>`.

**Comment by ConcaveTrillion** [comment]
pushed the fixes for these items. A few questions on these:

1. Are the indentations in other poems also interjections, and can be removed? They occur in 'dialogue.'
  - Black Beetles in Amber - "Incivism", "A Vision of Resurrection"
  - Shapes of Clay - "The Humorist", "Land of the Pilgrim’s Pride", "A Future Conversation", "The Psoriad", "An Alibi"

2. In the dramatis personae, is this the right capitalization for some of the 'group personas': 'Chorus of Foreign Voters', 'Chorus of Coffins', 'Spirit of Broken Hopes', etc.?

3. Should the 'Scene' headers (e.g. "The Brink of a Railway Cut, a Mile Deep") also be sentence case like the dramatis personae?

4. "together" class is split by a stage direction row, is the way I did this okay?

**Comment by EmmaSweeney** [comment]
1. The indents in those poems can stay.

2. Those look good.

3. I think those are fine.

4. The stage direction row shouldn't have `class="together"`. You can remove the class from the stage-direction row and the following song. The song can have an empty `<td>` element for the persona.

- Also, you can remove `rowspan="1"`. You only need to use the `rowspan` attribute if there are 2 or more lines spoken together.

**Comment by ConcaveTrillion** [comment]
Item 4 corrected! I don't think i have any more questions on the plays for now.

**Comment by EmmaSweeney** [comment]
Some minor changes:

- [ ] Where there are `<blockquote epub:type="z3998:verse">`, these don't need to be in a `<blockquote>`. The formatting is different in the page scans because the verse meter changes.

- [ ] In "The Two Cavees", it looks like `<p>Scene⁠—The Brink of a Railway Cut, a Mile Deep.</p>` and `<p>Time⁠—<time datetime="1875">1875</time>.</p>` belong at the end of the dramatis personae. This is where they typically appear in complete plays.

- [ ] In "The Two Cavees", it looks like `<i epub:type="z3998:stage-direction">Seizes <b epub:type="z3998:persona">Dead Cat</b> by the tail and swings it in act to throw.</i>` should follow the previous verse line. The stage direction isn't indented like the other stage direction rows. Tricky stuff!

- [ ] In "Metempsychosis", it looks like `<p>Scene⁠—A Small Lake in the Alleghany Mountains.</p>`  belongs at the end of the dramatis personae.

- [ ]  In "Metempsychosis", "Hello" should be on the same line as `<span>The while she sings my sentiments. <i epub:type="z3998:stage-direction">Enter <b epub:type="z3998:persona">Pitts-Stevens</b>.</i></span>`.

- [ ]  In "Metempsychosis", "Behold our queen!" should be on the same line as `<span>“Once on a time there lived”⁠—<i epub:type="z3998:stage-direction">Enter <b epub:type="z3998:persona"><abbr>Mrs.</abbr> Hayes</b>, as a tree walking.</i></span>`.

- [ ]  In "Metempsychosis", "`What, <em>you</em>?`" should be on the same line as `<span>Are all afloat. <i epub:type="z3998:stage-direction"><b epub:type="z3998:persona"><abbr>St.</abbr> John</b> discovers himself.</i></span>`.

- [ ] In "Slickens", it looks like `<p>Scene⁠—Yuba Dam.</p>` belongs at the end of the dramatis personae.

- [ ] In "Aspirants Three", it looks like `<p>Scene⁠—The Political Graveyard at Bone Mountain.</p>` belongs at the end of the dramatis personae.

- [ ]  In "Aspirants Three", "What? you!" should be on the same line as `<span>Are lifted into eminence. <i epub:type="z3998:stage-direction">Sees <b epub:type="z3998:persona">De Young</b>.</i></span>`.

- [ ] In "Aspirants Three", `<i epub:type="z3998:stage-direction">Sings.</i>` should be its own stage-direction row.

- [ ] In "Aspirants Three", it looks like the Spirit of Broken Hopes's dialog is a continuation of the song based on the [page scan formatting](https://archive.org/details/collectedworksof05bierrich/page/353/mode/1up).

- [ ] In "Aspirants Three", "Ah! had I known" should be on the same line as `<span>Then I’ll reform my life. <i epub:type="z3998:stage-direction">Reforms his life.</i></span>`.

- [ ] In "The Birth of the Rail", it looks like `<p>Scene⁠—The Dutch Flat Stage Road, at 12 <abbr>p.m.</abbr>, on a Night of 1864.</p>`  belongs at the end of the dramatis personae.

- [ ] In "A Bad Night", it looks like `<p>Scene⁠—A Cemetery in San Francisco.</p>`  belongs at the end of the dramatis personae.

- [ ] After rechecking the [page scans](https://archive.org/details/collectedworksof05bierrich/page/362/mode/1up), I don't see the stage direction `<p epub:type="z3998:stage-direction"><b epub:type="z3998:persona">Saralthia</b>, <b epub:type="z3998:persona">Nellibrac</b>, <b epub:type="z3998:persona">Grimghast</b>.</p>` at the beginning of "A Bad Night". You can remove it.

- [ ] In "A Bad Night", "Enough⁠—hale forth the stiff!" should be on the same line as `<span>Now what’s the hour? <i epub:type="z3998:stage-direction">Distant clock strikes thirteen.</i></span>`

**Comment by ConcaveTrillion** [comment]
I'll get to it! Sorry about all the changes.

**Comment by ConcaveTrillion** [comment]
Fixes:
- Corrected scene <p>'s to be after the </ul> in the dramatis personae. Sorry about that, I had them in the right place originally (needed to move just the high level stage directions to above the <table>).

- Moved the 'continued' verses that were interrupted by stage directions ('behold our queen' etc)

- Changed the Spirit of Broken Hopes' dialog to be in a blockquote song, removed indentation classes.

Question:
- For the Beginning of "A Bad Night", I noticed that there was a stage direction in the [original (scan)](https://archive.org/details/blackbeetlesinam00bier/page/263/mode/1up) collection, so I had included it (to me I thought it made sense to keep), but I can cut it if you'd prefer?

**Comment by EmmaSweeney** [comment]
Usually we follow what the latest published page scans. Since, that stage direction doesn't show up in a later edition it can be removed.

**Comment by EmmaSweeney** [comment]
*Usually we follow the latest published page scans.

**Comment by ConcaveTrillion** [comment]
Removed and pushed! I think its covers everything :-)
